#!/bin/bash

PKG=eric-3.9.4
WHERE=$SF/eric-ide

#PKG=eric-snapshot-20061029
#WHERE=http://www.die-offenbachs.de/detlev/snapshots

pushd ../SOURCES
if [ ! -f $PKG.tar.gz ]; then
    wget $WHERE/$PKG.tar.gz
fi

pushd ../BUILD
rm -rf $PKG
tar xfz ../SOURCES/$PKG.tar.gz
pushd $PKG
python install.py -b ~/usr/bin
popd # $PKG
popd # ../BUILD

# EOF
