#!/bin/bash

PKG=Jinja2-2.6

pushd ../SOURCES
if [ ! -f $PKG.tar.gz ]; then
    wget http://pypi.python.org/packages/source/J/Jinja2/$PKG.tar.gz
fi
popd


function version() {
    rm -rf $PKG
    tar xfz ../SOURCES/$PKG.tar.gz
    pushd $PKG
    $1 setup.py install
    popd # $PKG
}

pushd ../BUILD
version python2.5
version python2.6
version python2.7
version python3.1
version python3.2
popd # ../BUILD

# Local Variables: ***
# mode: sh ***
# End: ***
