#!/bin/bash

PKG=sympy

pushd ../SOURCES
if [ ! -e sympy ]; then
    git clone https://github.com/sympy/sympy.git
#    git clone git://github.com/sympy/sympy.git
else
    pushd sympy
    git pull
    popd sympy
fi
popd # ../SOURCES

function version() {
    rm -rf $PKG
    cp -r ../SOURCES/$PKG .
    pushd $PKG
    $1 setup.py build --force
    $1 setup.py install
    popd # $PKG
}

pushd ../BUILD
version python2.5
version python2.6
version python2.7
popd # ../BUILD

# Local Variables: ***
# mode: sh ***
# End: ***
