#!/bin/bash

WHERE=http://www.riverbankcomputing.com/static/Downloads/sip4
PKG=sip-4.12.3

pushd ../SOURCES
if [ ! -f $PKG.tar.gz ]; then
    wget $WHERE/$PKG.tar.gz
fi
popd # ../SOURCES

function version() {
    rm -rf $PKG
    tar xvfz ../SOURCES/$PKG.tar.gz
    pushd $PKG
    $1 configure.py -u
    make
    make install
    popd # $PKG
}

pushd ../BUILD
version python2.5
version python2.6
version python2.7
version python3.1
version python3.2
popd # ../BUILD # BUILD

# Local Variables: ***
# mode: sh ***
# End: ***
