#!/bin/bash

PKG=cElementTree-1.0.5-20051216

pushd ../SOURCES
if [ ! -f $PKG.tar.gz ]; then
    wget http://effbot.org/downloads/$PKG.tar.gz
fi
popd

pushd ../BUILD
rm -rf $PKG
tar xfz ../SOURCES/$PKG.tar.gz
pushd $PKG
python setup.py install
popd # $PKG
popd # ../BUILD

# Local Variables: ***
# mode: sh ***
# End: ***
