#!/bin/bash

PKG=ipython-0.10.2

pushd ../SOURCES
if [ ! -f $PKG.tar.gz ]; then
    wget http://ipython.scipy.org/dist/$PKG.tar.gz
fi
popd

pushd ../BUILD

rm -rf $PKG
tar xfz ../SOURCES/$PKG.tar.gz
pushd $PKG
python2.5 setup.py install
python2.6 setup.py install
python2.7 setup.py install
popd # $PKG

popd # ../BUILD

# Local Variables: ***
# mode: sh ***
# End: ***
