#!/bin/bash

set -x

#WHERE=http://www.riverbankcomputing.com/Downloads/Snapshots/sip4
#PKG=sip-snapshot-20061028
WHERE=http://www.riverbankcomputing.com/Downloads/sip4
PKG=sip-4.5.2

pushd ../SOURCES
if [ ! -f $PKG.tar.gz ]; then
    wget $WHERE/$PKG.tar.gz
fi
popd

pushd ../BUILD
rm -rf $PKG
tar xvfz ../SOURCES/$PKG.tar.gz
pushd $PKG
python configure.py -u
make
make install
popd # $PKG
popd # ../BUILD

# EOF