#!/bin/bash

PKG=numpy

pushd ../SOURCES
if [ ! -e numpy ]; then
    svn co http://svn.scipy.org/svn/numpy/trunk numpy
else
    pushd numpy
    svn up
    popd numpy
fi
popd # ../SOURCES

function version() {
    rm -rf $PKG
    cp -r ../SOURCES/$PKG .
    pushd $PKG
    if [ -f /etc/gentoo-release ]; then
	cat >site.cfg <<EOF
[atlas]
atlas_libs = lapack, blas, cblas, atlas
EOF
    fi
    $1 setup.py build --force 
    $1 setup.py install
    popd # $PKG
}

pushd ../BUILD
version python2.5
version python2.6
version python2.7
version python3.1
popd # ../BUILD

# Local Variables: ***
# mode: sh ***
# End: ***
