#!/bin/bash

VER=0.12
PKG=ipython-$VER

pushd ../SOURCES
if [ ! -f $PKG.tar.gz ]; then
    wget http://archive.ipython.org/release/$VER/$PKG.tar.gz
fi
popd

pushd ../BUILD

rm -rf $PKG
tar xfz ../SOURCES/$PKG.tar.gz
pushd $PKG
#python2.5 setup.py install
#python2.6 setup.py install
python2.7 setup.py install
#python3.1 setup.py install
#python3.2 setup.py install
popd # $PKG

popd # ../BUILD

# Local Variables: ***
# mode: sh ***
# End: ***
