#!/bin/bash

WHERE=http://www.riverbankcomputing.com/Downloads/PyQt3/GPL
PKG=PyQt-x11-gpl-3.17.3
JOBS=$(getconf _NPROCESSORS_ONLN)

pushd ../SOURCES
if [ ! -f $PKG.tar.gz ]; then
    wget $WHERE/$PKG.tar.gz
fi
popd

pushd ../BUILD
rm -rf $PKG
tar xfz ../SOURCES/$PKG.tar.gz
pushd $PKG
python configure.py -u -c -j $((2*$JOBS)) \
    -r -q $HOME/usr/lib/qt3.3 \
    CXXFLAGS+="-fno-exceptions" <<EOF
yes
EOF
make -j $JOBS
make install
popd # $PKG
popd # ../BUILD

# Local Variables: ***
# mode: sh ***
# End: ***
