#!/bin/bash

PKG=docutils-0.6

pushd ../SOURCES
if [ ! -f $PKG.tar.gz ]; then
    wget http://prdownloads.sourceforge.net/docutils/$PKG.tar.gz
fi
popd

function version() {
    rm -rf $PKG
    tar xfz ../SOURCES/$PKG.tar.gz
    pushd $PKG
    $1 setup.py install
    popd # $PKG
}

pushd ../BUILD
version python2.5
version python2.6
version python2.7
version python3.1
popd # ../BUILD

# Local Variables: ***
# mode: sh ***
# End: ***
