#!/bin/bash

PKG=Python-2.6.1
JOBS=$(getconf _NPROCESSORS_ONLN)

pushd ../SOURCES
if [ ! -f $PKG.tar.bz2 ]; then
    wget http://www.python.org/ftp/python/2.6.1/$PKG.tar.bz2
fi
popd

pushd ../BUILD
rm -rf $PKG
tar xfj ../SOURCES/$PKG.tar.bz2
pushd $PKG
./configure --prefix=$HOME/usr --with-cxx=g++ --enable-shared --with-pydebug
make -j $JOBS
make install
pushd Doc
make html
mkdir -p $HOME/usr/share/doc/python2.6
cp -R build/html $HOME/usr/share/doc/python2.6
popd # Doc
popd # $PKG
popd # ../BUILD

# Local Variables: ***
# mode: sh ***
# End: ***

