#!/bin/bash

PKG=scipy

pushd ../SOURCES
if [ ! -e scipy ]; then
    git clone git://github.com/scipy/scipy.git
else
    pushd scipy
    git pull
    popd scipy
fi
popd # ../SOURCES

function version() {
    rm -rf $PKG
    cp -r ../SOURCES/$PKG .
    pushd $PKG
    $1 setup.py build --force
    $1 setup.py install
    popd # $PKG
}

pushd ../BUILD
version python2.5
version python2.6
version python2.7
version python3.1
version python3.2
popd # ../BUILD

# Local Variables: ***
# mode: sh ***
# End: ***
