#!/bin/bash

PKG=numpy-1.0rc2

pushd ../SOURCES
if [ ! -f $PKG.tar.gz ]; then
    wget $SF/numpy/$PKG.tar.gz
fi
popd

pushd ../BUILD
rm -rf $PKG
tar xfz ../SOURCES/$PKG.tar.gz
pushd $PKG
if [ -f /etc/mandrakelinux-release ]; then
cat >site.cfg <<EOF
[atlas]
library_dirs = /usr/lib
atlas_libs = lapack, f77blas, cblas, atlas
EOF
fi
python setup.py install
popd # $PKG
popd # ../BUILD

# Local Variables: ***
# mode: sh ***
# End: ***
