#!/bin/bash

WHERE=http://www.riverbankcomputing.com/static/Downloads/PyQt4
PKG=PyQt-x11-gpl-4.9.1
JOBS=$(getconf _NPROCESSORS_ONLN)

pushd ../SOURCES
if [ ! -f $PKG.tar.gz ]; then
    wget $WHERE/$PKG.tar.gz
fi
popd

function version() {
    rm -rf $PKG
    tar xfz ../SOURCES/$PKG.tar.gz
    pushd $PKG
    $1 configure.py -u -a -c -j $((2*$JOBS)) \
        -q $HOME/usr/lib/qt4.8/bin/qmake \
        CXXFLAGS+="-fno-exceptions" <<EOF
yes
EOF
    make -j $JOBS
    make install
    mkdir -p $HOME/usr/share/doc/PyQt4
    cp -R doc/* $HOME/usr/share/doc/PyQt4
    popd # PKG
}

pushd ../BUILD
version python2.5
version python2.6
version python2.7
version python3.1
version python3.2
popd # ../BUILD

# Local Variables: ***
# mode: sh ***
# End: ***

