#!/bin/bash

WHERE=http://www.riverbankcomputing.com/static/Downloads/PyQt4
PKG=PyQt-x11-gpl-snapshot-4.7.3-4cf6d2fa926f
JOBS=$(getconf _NPROCESSORS_ONLN)

pushd ../SOURCES
if [ ! -f $PKG.tar.gz ]; then
    wget $WHERE/$PKG.tar.gz
fi
popd

pushd ../BUILD
rm -rf $PKG
tar xfz ../SOURCES/$PKG.tar.gz
pushd $PKG
python configure.py -u -a -c -j $((2*$JOBS)) \
    -q $HOME/usr/lib/qt4.6/bin/qmake \
    CXXFLAGS+="-fno-exceptions" <<EOF
yes
EOF
make -j $JOBS
make install
mkdir -p $HOME/usr/share/doc/PyQt4
cp -R doc/* $HOME/usr/share/doc/PyQt4
popd # PKG

rm -rf $PKG
tar xfz ../SOURCES/$PKG.tar.gz
pushd $PKG
python3 configure.py -u -a -c -j $((2*$JOBS)) \
    -q $HOME/usr/lib/qt4.6/bin/qmake \
    CXXFLAGS+="-fno-exceptions" <<EOF
yes
EOF
make -j $JOBS
make install
popd # PKG

popd # ../BUILD

# EOF