#!/bin/bash

PKG=matplotlib-0.90.0

pushd ../SOURCES
if [ ! -f $PKG.tar.gz ]; then
    wget $SF/matplotlib/$PKG.tar.gz
fi
popd

pushd ../BUILD
rm -rf $PKG
tar xfz ../SOURCES/$PKG.tar.gz
pushd $PKG
python setup.py install
popd # $PKG
popd # ../BUILD

# Local Variables: ***
# mode: sh ***
# End: ***
