#!/bin/bash

pushd ..
if [ ! -d SOURCES ]; then
    mkdir SOURCES
fi
if [ ! -d BUILD ]; then
    mkdir BUILD
fi
popd

./build-python
./build-pychecker
./build-numarray
./build-numeric
./build-numpy
./build-scipy
./build-gccxml
./build-qt3.3
./build-qt4.1
./build-qscintilla1
./build-simage
./build-coin-qt3
./build-coin-qt4
./build-soqt-qt3
./build-soqt-qt4
./build-sip
./build-pyqt
./build-pyqt4
./build-qwt
./build-qwtplot3d

# Local Variables: ***
# mode: sh ***
# End: ***
