#!/bin/bash

PKG=scipy-0.5.1

pushd ../SOURCES
if [ ! -f $PKG.tar.gz ]; then
    wget $SF/scipy/$PKG.tar.gz
fi
popd

pushd ../BUILD
rm -rf $PKG
tar xfz ../SOURCES/$PKG.tar.gz
pushd $PKG
python setup.py install
popd # $PKG
popd # ../BUILD

# Local Variables: ***
# mode: sh ***
# End: ***
