#!/bin/bash

PKG=pychecker-0.8.18

pushd ../SOURCES
if [ ! -f $PKG.tar.gz ]; then 
    wget $SF/pychecker/$PKG.tar.gz
fi

pushd ../BUILD

rm -rf $PKG
tar xfz ../SOURCES/$PKG.tar.gz
pushd $PKG
python2.6 setup.py install
popd # $PKG

popd # ../BUILD

# EOF
