#!/bin/bash

WHERE=http://www.riverbankcomputing.com/Downloads/Snapshots/PyQt4
PKG=PyQt-x11-gpl-4.3-snapshot-20071116
JOBS=$(getconf _NPROCESSORS_ONLN)

pushd ../SOURCES
if [ ! -f $PKG.tar.gz ]; then
    wget $WHERE/$PKG.tar.gz
fi
popd

pushd ../BUILD
rm -rf $PKG
tar xfz ../SOURCES/$PKG.tar.gz
pushd $PKG
python configure.py -u -c -j $((2*$JOBS)) \
    -q /home/packer/usr/lib/qt4.3/bin/qmake \
    CXXFLAGS+="-fno-exceptions" <<EOF
yes
EOF
make -j $JOBS
make install
mkdir -p $HOME/usr/share/doc/PyQt4
cp -R doc/* $HOME/usr/share/doc/PyQt4
popd # PKG
popd # ../BUILD

# EOF
