#!/bin/bash

PKG=SoQt-1.4.1
JOBS=$(getconf _NPROCESSORS_ONLN)

pushd ../SOURCES
if [ ! -f $PKG.tar.gz ]; then
    wget http://ftp.coin3d.org/coin/src/$PKG.tar.gz
fi
popd

pushd ../BUILD
rm -rf $PKG
tar xfz ../SOURCES/$PKG.tar.gz
pushd $PKG
./configure --prefix $HOME/usr/lib/qt4.4 --with-qt=$HOME/usr/lib/qt4.4
make -j $JOBS
make install

doxygen -u sogui.doxygen
cat >> sogui.doxygen << EOF
GENERATE_HTML = yes
HTML_HEADER =
HTML_FOOTER =
HTML_STYLESHEET =
HAVE_DOT = yes
EOF
doxygen sogui.doxygen
rm -f html/*.{map,md5} html/Makefile*
mkdir -p $HOME/usr/share/doc/$PKG
cp -r html $HOME/usr/share/doc/$PKG

popd # $PKG
popd # ../BUILD

# Local Variables: ***
# mode: sh ***
# End: ***

