#!/bin/bash

PKG=gccxml

pushd ../BUILD
if [ ! -e $PKG ]; then
    cvs -d :pserver:anoncvs@www.gccxml.org:/cvsroot/GCC_XML co gccxml
fi
pushd $PKG
cvs up -dP
popd # $PKG

rm -rf gccxml-build
mkdir gccxml-build
pushd gccxml-build
cmake ../gccxml -DCMAKE_INSTALL_PREFIX:PATH=$HOME/usr
make
make install
popd # gccxml-build
popd # ../BUILD

# EOF