#!/bin/bash

PKG=pyglet-1.1.2

pushd ../SOURCES
if [ ! -f $PKG.tar.gz ]; then
    wget http://pyglet.googlecode.com/files/$PKG.tar.gz
fi
popd

pushd ../BUILD
rm -rf $PKG
tar xfz ../SOURCES/$PKG.tar.gz
pushd $PKG
python setup.py install
popd # $PKG
popd # ../BUILD

# Local Variables: ***
# mode: sh ***
# End: ***
