#!/bin/bash

PKG=guidata-1.2.1

pushd ../SOURCES
if [ ! -f $PKG.zip ]; then
    wget $SF/guidata/$PKG.zip
fi
popd

function version() {
    rm -rf $PKG
    unzip ../SOURCES/$PKG.zip
    pushd $PKG
    $1 setup.py install
    popd # $PKG
}

pushd ../BUILD
version python2.5
version python2.6
version python2.7
#version python3.1
popd # ../BUILD

# Local Variables: ***
# mode: sh ***
# End: ***
