#!/bin/bash

WHERE=http://www.riverbankcomputing.com/static/Downloads/PyQt3
PKG=PyQt-x11-gpl-snapshot-3.18.2-29855a84d8b6

JOBS=$(getconf _NPROCESSORS_ONLN)

pushd ../SOURCES
if [ ! -f $PKG.tar.gz ]; then
    wget $WHERE/$PKG.tar.gz
fi
popd

function version() {
    rm -rf $PKG
    tar xfz ../SOURCES/$PKG.tar.gz
    pushd $PKG
    $1 configure.py -u -c -j $((2*$JOBS)) \
	-r -q $HOME/usr/lib/qt3.3 \
	CXXFLAGS+="-fno-exceptions" <<EOF
yes
EOF
    make -j $JOBS
    make install
    popd # $PKG
}

pushd ../BUILD
version python2.5
version python2.6
version python2.7
popd # ../BUILD

# Local Variables: ***
# mode: sh ***
# End: ***
