#!/bin/bash

WHERE=http://www.die-offenbachs.de/detlev/snapshots4/
PKG=eric4-snapshot-20070325

pushd ../SOURCES
if [ ! -f $PKG.tar.gz ]; then
    wget $WHERE/$PKG.tar.gz
fi

pushd ../BUILD
rm -rf $PKG
tar xfz ../SOURCES/$PKG.tar.gz
pushd $PKG
python install.py -b ~/usr/bin
popd # $PKG
popd # ../BUILD

# EOF
