#!/bin/bash

WHERE=http://www.riverbankcomputing.co.uk/static/Downloads/QScintilla2/
PKG=QScintilla-gpl-2.5.1
JOBS=$(getconf _NPROCESSORS_ONLN)

pushd ../SOURCES
if [ ! -f $PKG.tar.gz ]; then
    wget $WHERE/$PKG.tar.gz
fi
popd

function version() {
    rm -rf $PKG
    tar xfz ../SOURCES/$PKG.tar.gz
    pushd $PKG/Qt4
    qmake
    make -j $JOBS
    make install
    popd # $PKG/Qt4
    pushd $PKG/designer-Qt4
    qmake
    make
    make install
    popd # $PKG/designer-Qt4
    pushd $PKG/Python
    $1 configure.py -j $JOBS
    make -j $JOBS
    make install
    popd # $PKG/Python
}

pushd ../BUILD
version python2.5
version python2.6
version python2.7
version python3.1
version python3.2
popd # ../BUILD

# Local Variables: ***
# mode: sh ***
# End: ***
