#!/bin/bash

WHERE=http://www.riverbankcomputing.com/Downloads/Snapshots/PyQt4
PKG=PyQt-x11-gpl-4-snapshot-20061022
JOBS=$(getconf _NPROCESSORS_ONLN)

pushd ../SOURCES
if [ ! -f $PKG.tar.gz ]; then
    wget $WHERE/$PKG.tar.gz
fi
popd

pushd ../BUILD
rm -rf $PKG
tar xfz ../SOURCES/$PKG.tar.gz
pushd $PKG
python configure.py -a -c -j $((2*$JOBS)) \
    -q /home/packer/usr/lib/qt4.2/bin/qmake \
    CXXFLAGS+="-fno-exceptions" <<EOF
yes
EOF
make -j $JOBS
make install
popd # PKG
popd # ../BUILD

# EOF