#!/bin/bash

PKG=Sphinx-1.1.3

pushd ../SOURCES
if [ ! -f $PKG.tar.gz ]; then
    wget http://pypi.python.org/packages/source/S/Sphinx/$PKG.tar.gz
fi
popd

function version() {
    rm -rf $PKG
    tar xfz ../SOURCES/$PKG.tar.gz
    pushd $PKG
    $1 setup.py install
    popd # $PKG
}

pushd ../BUILD
version python2.5
version python2.6
version python2.7
popd # ../BUILD

# Local Variables: ***
# mode: sh ***
# End: ***
