#!/bin/bash

WHERE=http://www.riverbankcomputing.com/static/Downloads/sip4
PKG=sip-4.7.5-snapshot-20080412

pushd ../SOURCES
if [ ! -f $PKG.tar.gz ]; then
    wget $WHERE/$PKG.tar.gz
fi
popd

pushd ../BUILD
rm -rf $PKG
tar xvfz ../SOURCES/$PKG.tar.gz
pushd $PKG
python configure.py -u
make
make install
popd # $PKG
popd # ../BUILD

# EOF
