#!/bin/bash

PKG=Python-2.5.1
JOBS=$(getconf _NPROCESSORS_ONLN)

pushd ../SOURCES
if [ ! -f $PKG.tar.bz2 ]; then
    wget http://www.python.org/ftp/python/2.5.1/$PKG.tar.bz2
fi
popd

pushd ../BUILD
rm -rf $PKG
tar xfj ../SOURCES/$PKG.tar.bz2
pushd $PKG
OPT="-O3 -Wall" ./configure --prefix=$HOME/usr --with-cxx=g++ --enable-shared
make -j $JOBS
make install
pushd Doc
make html
mkdir -p $HOME/usr/share/doc/python2.5
cp -R html $HOME/usr/share/doc/python2.5
popd # Doc
popd # $PKG
popd # ../BUILD

# Local Variables: ***
# mode: sh ***
# End: ***

