#!/bin/bash

PKG=numpy-1.0rc1

pushd ../SOURCES
if [ ! -f $PKG.tar.gz ]; then
    wget $SF/numpy/$PKG.tar.gz
fi
popd

pushd ../BUILD
rm -rf $PKG
tar xfz ../SOURCES/$PKG.tar.gz
pushd $PKG
python setup.py install
popd # $PKG
popd # ../BUILD

# Local Variables: ***
# mode: sh ***
# End: ***
